### ISSUE TITLE
Grouping elements 

### ISSUE THREAD

**Issue by robertKamrowski** [giovanni-bertoncelli/ngx-konva#13]
Hi, this package works amazing! I would like to ask about one problem that I'm struggling with. 

This is my template:

![image](https://github.com/ctinnovation/ngx-konva/assets/81650422/f99906db-67e8-4f37-9447-7f6045732642)

And it always creates just one group, even though there are plenty of them :( 

Maybye I'm doing something wrong ? 

It would be awesome to hear your feedback.

**Comment by giovanni-bertoncelli** [comment]
Hi @robertKamrowski , thank you for your feedback. Sadly I can't check for the issue in the next few days. In the meantime would you please add a reproduction example?
There may be probably some issue with the ko-group implementation

**Comment by robertKamrowski** [comment]
Here is a small repro, with issue described in readme.md:  [Link](https://github.com/robertKamrowski/ngx-konva-grouping)

**Comment by robertKamrowski** [comment]
@giovanni-bertoncelli I think I have found the solution, can You have a look on that: [Pull Request](https://github.com/ctinnovation/ngx-konva/pull/14) ?

**Comment by giovanni-bertoncelli** [comment]
@robertKamrowski will release soon as 16.0.14
